version: "3.9"
services:
  app:
    container_name: cryptomarket-app
    build: .
    ports:
      - "8001:443"
    tty: true
    volumes:
      - ./:/app
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - network
  db:
    container_name: cryptomarket-db
    image: mariadb:10.5.8
    restart: always
    volumes:
      - ./var/db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      TZ: Europe/Paris
    networks:
      - network
  phpmyadmin:
    container_name: cryptomarket-pma
    image: phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
    networks:
      - network
volumes:
  caddy_data:
  caddy_config:
networks:
  network:
